image: nextmetaphor/dockerized-alpine-angular:latest
pages:
  stage: deploy
  script:
    - npm install
    - ng build --base-href /cloud-blueprints-ui/
    - mkdir -p public
    - mv dist/cloud-blueprints-ui/* public/
  artifacts:
    paths:
      - public
  only:
    - main